version: '3.8'

services:
    db_lutece_site:
        image: mariadb:10.5
        container_name: db_lutece_site
        ports:
            - "3308:3306"
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=lutece_db
        volumes:
           - ./mysql-data:/var/lib/mysql

    lutece_site:
        build:
            context: ./site-lutece
            dockerfile: Dockerfile
        container_name: site-lutece
        ports:
            - 8080:8080
        restart: unless-stopped
        depends_on:
            - db_lutece_site
        volumes:
            -   ./volume-site-lutece:/usr/local/tomcat/webapps/ROOT
            # logs catalina
            -  ./logs:/usr/local/tomcat/logs
