version: '3.8'

services:
    db:
        image: mariadb:10.5
        container_name: db
        ports:
            - "3308:3306"
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=lutece_db
        volumes:
           - ./mysql-data:/var/lib/mysql

    lutece_site:
        build:
            context: ./site-lutece
            dockerfile: Dockerfile
        container_name: site-lutece
        ports:
            - 8080:8080
        depends_on:
            - db
        volumes:
            -   ./volume-site-lutece:/usr/local/tomcat/webapps/ROOT
